// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using UserAuthService.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Xml;

namespace UserAuthService.Infrastructure.Persistence;

public partial class AuthServiceDBContext : DbContext
{
    public AuthServiceDBContext(DbContextOptions<AuthServiceDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<User>()
                .Property(u => u.UserId)
                .HasDefaultValueSql("NEWID()");
    }
}